### ISSUE TITLE
No PV-String Data with V1.0.6

### ISSUE THREAD

**Issue by creecool** [git-kick/ioBroker.e3dc-rscp#112]
After the installation of Version 1.0.6 the system does not receive data from/for the PV String 1 & 2.
There are no error information in the Logfile.

After a downgrade to 1.0.5 it is working. 

Picture V1.0.6

![image](https://user-images.githubusercontent.com/62263121/179498628-f5dc977f-f046-4180-9230-5d8b63867e76.jpeg)

Picture V1.0.5
![image](https://user-images.githubusercontent.com/62263121/179498744-3cac9c45-915d-4ec0-a02a-6e94c6452b15.jpeg)

**Comment by creecool** [comment]
Hi, I have installed the version 1.0.6 via GitHub and now it is working. I will test it for the next days. 
I have an other question, where can I find the actual software version f.e S10_2022_02x of the device? Is this working via RSCP request? 

Thx

**Comment by git-kick** [comment]
No bug.
