### ISSUE TITLE
Wallbox labels write enabled

### ISSUE THREAD

**Issue by Matis-11** [git-kick/ioBroker.e3dc-rscp#118]
It would be great help for remote controlling the car charging process if this two labels whould be write enabled as well:

e3dc-rscp.0.EMS.BATTERY_BEFORE_CAR_MODE
e3dc-rscp.0.EMS.BATTERY_TO_CAR_MODE

Thanks a lot.

**Comment by git-kick** [comment]
@Matis-11 thanks for you request.

Please see [Issue#106](https://github.com/git-kick/ioBroker.e3dc-rscp/issues/106) for my explanation (German) why I am not able to support wallbox write tags. Still waiting for a contributor to jump in.
