### ISSUE TITLE
Wallbox / E3DC

### ISSUE THREAD

**Issue by christianreiss** [git-kick/ioBroker.e3dc-rscp#123]
Hey :-)

Great work! I have an E3DC with a E3DC Wallbox; is it possible to STOP the charging via rscp? I would love my Twingo to not be fully charged and stop it at a certain percentage :)

Everything is done and working, except the Stop charging part...

**Comment by git-kick** [comment]
@christianreiss, thanks for you request.

Please see https://github.com/git-kick/ioBroker.e3dc-rscp/issues/106 for my explanation (German) why I am not able to support wallbox write tags. Still waiting for a contributor to jump in.
