### ISSUE TITLE
Warning: Received data type ERROR: RSCP_ERR_NOT_AVAILABLE (6) - tag TAG_PVI_REQ_FREQUENCY_UNDER_OVER (0x2000080)

### ISSUE THREAD

**Issue by SurfGargano** [git-kick/ioBroker.e3dc-rscp#126]
Die neueren S10 haben wohl nicht mehr diese Abfrage.
Vorschlag : In der Konfiguration der Instanz / Abfrageintervalle außer S/M/L  auch N für None zulassen.
Dann kann man die Abfrage einfach ausschalten. Würde auch den Traffic reduzieren.

**Comment by git-kick** [comment]
Merged into master.
Will be released with v1.0.9
