### ISSUE TITLE
Funktion: Manuelle Speicherladung

### ISSUE THREAD

**Issue by Borilu** [git-kick/ioBroker.e3dc-rscp#142]
Ist es möglich eine manuelle Speicherladung anzustoßen? Also x Wh über das Netz in die Batterie zu laden?
Wenn ich "e3dc-rscp.0.EMS.MANUAL_CHARGE_ACTIVE" auf true setze passiert leider nichts.
Hintergrund:
Bei einem dynamischen Stromtarif möchte ich bei günstigen Strompreisen die Batterie auf 100% bringen um sie dann bei hohen Strompreisen zu entleeren.
Vielen Dank für die Hilfe.

**Comment by git-kick** [comment]
![grafik](https://user-images.githubusercontent.com/8932938/216836463-077d6286-9716-44bb-bb0a-32e27feb0c8a.png)
An dem Schloß-Symbol links und an der Rolle "indicator" bzw. "value" kann man erkennen, dass dies beides read-only-tags sind (wären sie schreibbar, hätten sie die Rolle "switch" bzw. "level").

Wie man die manuelle Speicherladung anstößt, kann ich aus der Tagliste nicht erkennen; evtl. hat das `SET_POWER_MODE` Tag etwas damit zu tun, aber das ist reine Spekulation.

**Comment by Borilu** [comment]
Kann ich bestätigen.
![image](https://user-images.githubusercontent.com/72373010/217045960-ad005a3f-f962-41f2-947f-1385d63f12a4.png)
Grid_Charge startet die Speicherladung aus dem Netz. Danke

**Comment by git-kick** [comment]
Sehr gut, dass es klappt.
