### ISSUE TITLE
SG Ready status

### ISSUE THREAD

**Issue by nase30** [git-kick/ioBroker.e3dc-rscp#150]
Ist it possible to get the SG Ready status as well (Relais A and B) ?

**Comment by git-kick** [comment]
I don't know what "SG ready status" means.

If you want find potential RSCP Tags containing the information you need, I recommend to look into the official tag list, an Excel contained in the RscpExample:
![Screenshot_20230416-221037](https://user-images.githubusercontent.com/8932938/232339650-c34cce20-c12e-4a04-bf82-0f90330bb375.png)

**Comment by nase30** [comment]
I reviewed all the RSCP Data on iobroker and haven't found the SG-Ready status, nor in the documentation. May be they are named different and I'm not aware of. I'm looking for the status of the SG0 and SG1 actor.
![image](https://user-images.githubusercontent.com/97479897/232344898-d5570c16-ed4a-4b99-a767-fcf6c72e57b1.png)

**Comment by git-kick** [comment]
Seems like SG ready is a separate interface.
If you have reviewed all RSCP tags and the information you are looking for is not there, then the e3dc-rscp adapter cannot fulfill your need.
