### ISSUE TITLE
Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range with version 1.2.0

### ISSUE THREAD

**Issue by SurfGargano** [git-kick/ioBroker.e3dc-rscp#154]
**Describe the bug**  
Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range with adapter version 1.2.0
with version 1.1.2 there is no error.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
no error

**Screenshots & Logfiles**  
<html>
<body>

host.raspberrypi | 2023-04-24 13:55:48.562 | error | instance system.adapter.e3dc-rscp.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
e3dc-rscp.0 | 2023-04-24 13:55:47.913 | error | Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 6716. Received 36921
e3dc-rscp.0 | 2023-04-24 13:55:47.912 | error | RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 6716. Received 36921 at new NodeError (node:internal/errors:399:5) at boundsError (node:internal/buffer:88:9) at Buffer.readUInt32LE (node:internal/buffer:222:5) at E3dcRscp.parseTlv (/opt/iobroker/node_modules/iobroker.e3dc-rscp/main.js:1242:27) at E3dcRscp.processFrame (/opt/iobroker/node_modules/iobroker.e3dc-rscp/main.js:1342:26) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.e3dc-rscp/main.js:522:10) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10)

</body>
</html>
**Versions:**  
 - Adapter version: <1.2.0>
 - JS-Controller version: <4.0.24> 
 - Node version: <v18.15.0> 
 - Operating system: <debian 64 bit>

**Additional context**

**Comment by git-kick** [comment]
v1.2.0 was not published in ioBroker. In fact, it is an erroneous build and marked 'deprecated' on npm. Please downgrade to v1.1.2

**Comment by git-kick** [comment]
You can now try v1.2.1 from the "latest" channel.
Not "stable", no guarantees ;-)

**Comment by SurfGargano** [comment]
V1.2.1 : installation ok, works without error messages
