### ISSUE TITLE
Some TAG (Info) are not in the list 

### ISSUE THREAD

**Issue by SurfGargano** [git-kick/ioBroker.e3dc-rscp#156]
**Describe the bug**  
Some items of the interval are not in the list

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
<html>
<body>

-- | -- | -- | --
e3dc-rscp.0 | 2023-04-28 09:00:21.906 | warn | TAG_INFO_REQ_GET_FS_USAGE has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.905 | warn | TAG_INFO_REQ_GET_FACILITY has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.905 | warn | TAG_INFO_REQ_GUI_TARGET has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.905 | warn | TAG_INFO_REQ_SW_RELEASE has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.904 | warn | TAG_INFO_REQ_TIME_ZONE has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.903 | warn | TAG_INFO_REQ_UTC_TIME has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.903 | warn | TAG_INFO_REQ_TIME has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.903 | warn | TAG_INFO_REQ_DHCP_STATUS has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.902 | warn | TAG_INFO_REQ_DNS has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.901 | warn | TAG_INFO_REQ_GATEWAY has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.899 | warn | TAG_INFO_REQ_MAC_ADDRESS has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.898 | warn | TAG_INFO_REQ_SUBNET_MASK has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.898 | warn | TAG_INFO_REQ_IP_ADDRESS has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.897 | warn | TAG_INFO_REQ_A35_SERIAL_NUMBER has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.896 | warn | TAG_INFO_REQ_MODULES_SW_VERSIONS has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.895 | warn | TAG_INFO_REQ_PRODUCTION_DATE has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.894 | warn | TAG_INFO_REQ_SERIAL_NUMBER has no assigned polling interval - assuming 'M' - please check io-package.json
e3dc-rscp.0 | 2023-04-28 09:00:21.888 | warn | TAG_EP_REQ_EP_RESERVE has no assigned polling interval - assuming 'M' - please check io-package.json

</body>
</html>

**Versions:**  
 - Adapter version: <1.2.1>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by git-kick** [comment]
Did you cleanup your adapter config?
See https://github.com/git-kick/ioBroker.e3dc-rscp#reuse-of-adapter-configuration
