### ISSUE TITLE
I have set the TAG_PVI_REQ_FREQUENCY_UNDER_OVER to 'N' , but it shows a warning.

### ISSUE THREAD

**Issue by SurfGargano** [git-kick/ioBroker.e3dc-rscp#157]
**Describe the bug**  
I have set the TAG_PVI_REQ_FREQUENCY_UNDER_OVER to 'N' , but it shows a warning.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
With disabled tag by 'N' it should not show a warning 

**Screenshots & Logfiles**  
<html>
<body>

3dc-rscp.0 | 2023-04-28 09:11:00.519 | warn | Received data type ERROR: RSCP_ERR_NOT_AVAILABLE (6) - tag TAG_PVI_REQ_FREQUENCY_UNDER_OVER (0x2000080)
-- | -- | -- | --

</body>
</html>
**Versions:**  
 - Adapter version: <1.2.1>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by git-kick** [comment]
Could you please retry after #156 is solved for you. I suspect the same root cause. Thanks.

**Comment by SurfGargano** [comment]
I have delete the instance and add a new one, but the problem still remains

**Comment by SurfGargano** [comment]
yes

**Comment by git-kick** [comment]
I think I have found the root cause: the adapter sends 5 initial requests for "all data", ignoring the S/M/L/N-setting.
Is it true that you see max. 5 of those warnings after every instance start?

**Comment by SurfGargano** [comment]
Sorry, in the Moment I can't check.Am 06.05.23, 11:09 schrieb Uli Kick ***@***.***>:

   
  I think I have found the root cause: the adapter sends 5 initial requests for "all data", ignoring the S/M/L/N-setting. Is it true that you see max. 5 of those warnings after every instance start?

**Comment by git-kick** [comment]
Release v1.2.2 available at npm (not yet "stable" in ioBroker-Repo).
