### ISSUE TITLE
IDLE PERIOD ACTIVE funktioniert nicht

### ISSUE THREAD

**Issue by git-kick** [git-kick/ioBroker.e3dc-rscp#158]
Hallo.  
Ich nutze den Adapter jetzt auch schon eine ganze Zeit und bin damit sehr zufrieden.  Da die Wetterprognose von E3DC aber nicht immer funktioniert (Ticket habe ich aufgemacht), würde ich gerne das Scharfschalten der Sperrzeiten für das Laden der Batterie ereignisgesteuert selbst vornehmen wollen. Ich habe mal versucht den Wert der jeweiligen Objekte "IDLE PERIOD ACTIVE" zu schalten.  Mir wird zwar ein anderer Wert angezeigt, mein Hauskraftwerk übernimmt den Wert aber nicht.  Müsste / Könnte der Adapter in dieser Hinsicht noch erweitert werden?
Herzliche Grüße an Alle Stefan

_Originally posted by @RSScheible in https://github.com/ioBroker/AdapterRequests/issues/676#issuecomment-1534663065_

**Comment by git-kick** [comment]
@RSScheible
`IDLE_PERIOD_ACTIVE` unterstützt der Adapter bereits und in meinen Tests hat es funktioniert.
Sollte hier ein Fehler passieren den ich untersuchen soll, bitte den Javascript-Code und das debug-log eines "Schaltversuchs" posten. (Anleitung siehe Adapter-README).

Man kann die Ladeleistung auch stufenlos steuern mit
    `setState( 'e3dc-rscp.0.EMS.MAX_CHARGE_POWER', newLimit );`
    `setState( 'e3dc-rscp.0.EMS.POWER_LIMITS_USED', true );`

**Comment by RSScheible** [comment]
Hallo Uli, 

 

vielen Dank für die schnelle Antwort und vielen Dank für die Entwicklung dieses tollen Adapters.  Ich bin zwar schon länger E3DC Nutzer (seit 2018), in den Themen Programmierung etc. aber noch nicht so fit.  Also ich habe vor Jahrzehnten schon einmal programmiert (Fortran, Pascal, PL1), muss mich jetzt aber in die neuen Sprachen noch etwas einarbeiten.  Im IOBroker nutze ich der Einfachheit halber noch Blocky.  

 

Aktuell nutze ich über Deinen Adapter die Information des Ladezustandes und  der Abregelung, erzeuge eine Pushover Meldung auf mein Handy, so dass ich aktuell noch manuell mein EAuto dann lade oder andere Verbraucher anschalte.  Das funktioniert schon seit mehreren Monaten problemlos. Das sind aber nur LESEZUGRIFFE.

 

Da meine Anlage leider die 70% Grenze hat und laut Netzbetreiber die aktuell geltenden Regeln diese Abregelung noch bleibt, versuche ich mit der Wetterprognose zu optimieren, sprich das Laden der Batterie in den Tagesleistungspeak zu schieben.  Die Wetterprognose funktioniert aber zur Zeit nicht.  E3DC ist informiert, ist vermutlich aber nicht oben auf der Priorität.

 

Ich bin dann wieder auf Deinen Adapter gestossen und wolle sehen, ob ich auch SCHREIBEND den bzw. die relevanten Parameter verändern kann.  

 

Konkret:  Ich habe im IO Broker im Reiter Objekte im Ordner Deines Adapters den Wert für IDLE PERIOD ACTIVE eines Wochentages umgeschaltet.  Der neue Wert wurde mir auch im IOBroker Objekt direkt angezeigt. Wenn ich dann aber auf die APP gehe und mir dann in den Smart Funktionen die Sperrzeiten ansehe, hat sich nichts verändert.  Insofern vermute ich, dass die Datenübertragung zum E3DC nicht richtig funktioniert. 

Der umgekehrte Weg, Ändern der Sperrzeiten für das Laden im E3DC Portal / APP funktioniert.  Die neuen Daten werden im IOBroker nach kurzer Zeit angezeigt. 

 

Ich hatte auch in Deiner Beschreibung gelesen, dass man ggf. den Adapter nach einem Update neu Installieren muss.  Das habe ich bisher noch nicht gemacht. 

 

Herzliche Grüße

 

 

Stefan

**Comment by git-kick** [comment]
Hallo Stefan,

es freut mich, dass der Adapter Nutzen bringt!

Ob du zur Programmierung Javascript oder Blockly nutzt, sollte hinsichtlich Adapter egal sein. Ich habe Blockly noch nicht benutzt, gehe aber davon aus, dass die Variablen überall so heißen wie im Objektbaum von ioBroker.

Der Anwendungsfall „Vermeidung der Abregelung“ ist bei mir genauso. Ich steuere seit 2 Jahren die E3/DC über den Adapter, die Schreibzugriffe sind ja das „Salz in der Suppe“. Das funktioniert definitiv bei meiner S10E-Anlage.

Leider lieferst du in deiner Mail keine weiteren Information über den „Fehler“, der bei dir auftritt. 
Bitte versuche, meine Kommentare genau zu lesen und darauf zu reagieren, in diesem Fall:

> Sollte hier ein Fehler passieren den ich untersuchen soll, bitte den Javascript-Code und das debug-log eines "Schaltversuchs" posten. (Anleitung siehe Adapter-[README](https://github.com/git-kick/ioBroker.e3dc-rscp#readme)).

Ich brauche ein debug-log aus deinem ioBroker, sonst kann ich _nichts_ tun (denn bei mir funktioniert ja alles). Im o.g. README [steht](https://github.com/git-kick/ioBroker.e3dc-rscp#bug-reports):
![grafik](https://user-images.githubusercontent.com/8932938/236504706-c202275a-ca78-40ea-aefc-40b239afd8ad.png)

> Man kann die Ladeleistung auch stufenlos steuern mit
> setState( 'e3dc-rscp.0.EMS.MAX_CHARGE_POWER', newLimit );
> setState( 'e3dc-rscp.0.EMS.POWER_LIMITS_USED', true );

Hast du das versucht? Damit könntest du nicht nur Ein-/Aus-Schalten, sondern dosiert laden.

Du kannst übrigens in github direkt antworten, dann wird der Thread schöner dargestellt und nicht mit Wiederholungen "zugemüllt": [Issue#158](https://github.com/git-kick/ioBroker.e3dc-rscp/issues/158) (für neue Themen bitte einen neuen Issue anlegen)

Grüße, Uli

**Comment by RSScheible** [comment]
Alles klar.  Vielen Dank.  Ich melde mich über Github sobald ich Deinen  Test gemacht habe.  Herzliche Grüße StefanMit freundlichen Grüßen Rolf-Stefan Scheible Tonwerkstraße 2369254 MalschAm 05.05.2023 um 17:50 schrieb Uli Kick ***@***.***>:﻿
Hallo Stefan,
es freut mich, dass der Adapter Nutzen bringt!
Ob du zur Programmierung Javascript oder Blockly nutzt, sollte hinsichtlich Adapter egal sein. Ich habe Blockly noch nicht benutzt, gehe aber davon aus, dass die Variablen überall so heißen wie im Objektbaum von ioBroker.
Der Anwendungsfall „Vermeidung der Abregelung“ ist bei mir genauso. Ich steuere seit 2 Jahren die E3/DC über den Adapter, die Schreibzugriffe sind ja das „Salz in der Suppe“. Das funktioniert definitiv bei meiner S10E-Anlage.
Leider lieferst du in deiner Mail keine weiteren Information über den „Fehler“, der bei dir auftritt.
Bitte versuche, meine Kommentare genau zu lesen und darauf zu reagieren, in diesem Fall:

Sollte hier ein Fehler passieren den ich untersuchen soll, bitte den Javascript-Code und das debug-log eines "Schaltversuchs" posten. (Anleitung siehe Adapter-README).

Ich brauche ein debug-log aus deinem ioBroker, sonst kann ich nichts tun (denn bei mir funktioniert ja alles). Im o.g. README steht:


Man kann die Ladeleistung auch stufenlos steuern mit
setState( 'e3dc-rscp.0.EMS.MAX_CHARGE_POWER', newLimit );
setState( 'e3dc-rscp.0.EMS.POWER_LIMITS_USED', true );

Hast du das versucht? Damit könntest du nicht nur Ein-/Aus-Schalten, sondern dosiert laden.
Du kannst übrigens in github direkt antworten, dann wird der Thread schöner dargestellt und nicht mit Wiederholungen "zugemüllt": Issue#158 (für neue Themen bitte einen neuen Issue anlegen)
Grüße, Uli

**Comment by RSScheible** [comment]
Ich habe heute den Apdapter noch einmal getestet und versucht die Ladung auf 500 Watt zu begrenzen.  Laut meiner E3DC App kommt aber diese Ladegrenze nicht an.  Anbei der Debug Log vom Adapter.  Mache ich etwas falsch?
[Logfile.txt](https://github.com/git-kick/ioBroker.e3dc-rscp/files/11411868/Logfile.txt)

**Comment by RSScheible** [comment]
[Logfile.txt](https://github.com/git-kick/ioBroker.e3dc-rscp/files/11411870/Logfile.txt)
Ich habe heute den Adapter getestet und eine Begrenzung auf 500 Watt für die Ladegrenze der Batterie eingegeben. Laut E3DC App kommt diese Grenze aber nicht an.  Was mach ich falsch? Anbei der Logfile.
HG Stefan

**Comment by git-kick** [comment]
> Hallo Uli, vielen Dank für die Hilfe. Mit den Befehlen in einem Java Script funktioniert das alles auch bei meiner Anlage. Jetzt habe ich nur noch eine Frage (eher eine Bestätigung). Mit den beiden setState Befehlen kann ich jetzt die Ladeleistung beliebig steuern, richtig? Also auch der Wert "Null" ist zugelassen, falls ich überhaupt nicht laden möchte.

Ja, bei mir funktioniert das auch mit 0 W.

**Comment by git-kick** [comment]
> [Logfile.txt](https://github.com/git-kick/ioBroker.e3dc-rscp/files/11411870/Logfile.txt) Ich habe heute den Adapter getestet und eine Begrenzung auf 500 Watt für die Ladegrenze der Batterie eingegeben. Laut E3DC App kommt diese Grenze aber nicht an. Was mach ich falsch? Anbei der Logfile. HG Stefan

Das logfile sieht gut aus, ich sehe keine "verdächtige" Meldung.
Die beiden Zeilen mit `queueSetValue` zeigen, dass der Adapter den Wert `500` und die Aktivierung `true` korrekt absendet.

Werden beide Werte (`500` & `true`) auch (1) im ioBroker object tree und (2) an der E3/DC-Anlage angezeigt?
Ich vermute die Antwort lautet (1) ja und (2) nein.

In dieser Situation bräuchte ich ein noch ausführlicheres logfile (silly/alles), um weiter zu forschen.

[Weiter oben](https://github.com/git-kick/ioBroker.e3dc-rscp/issues/158#issuecomment-1536576227) hast du geschrieben:
> Mit den Befehlen in einem Java Script funktioniert das alles auch bei meiner Anlage

Was genau hat da funktioniert?

**Comment by ArnoD15** [comment]
> Laut E3DC App kommt diese Grenze aber nicht an. 

In der App kann es sein das diese Verzögert übermittelt werden.
Prüfe das bitte mal direkt beim E3DC Hauskraftwerk in den Einstellungen, dort sollte es direkt umgestellt werden.


Du kannst dir auch mal mein Skript Charge-Control ansehen, ich denke, das macht genau das, was du benötigst.
- Funktionierende Wetterprognose
- Verhindern, dass die 70% Abriegelung erreicht wird durch intelligentes Laden der Batterie.
[Charge-Control](https://github.com/ArnoD15/iobroker_E3DC)

**Comment by RSScheible** [comment]
@Alle:  Herzlichen Dank für die Unterstützung.  Dank Eurer Hilfe kommt mir das Thema IOBroker und JavaScript viel schneller näher.  Das Problem hat sich jetzt vollständig geklärt.  Die Erklärung:  Das Problem saß mal wieder vor dem Computer.  Ich hatte vorher in den Einstellungen der E3DC APP für heute eine feste Ladesperrzeit eingetragen.  Die geht logischer Weise vor einer Veränderung der Ladeleistung.  Ich habe die Sperre rausgenommen und siehe da, es funktioniert.  
Aber das hat ja auch etwas gutes.  Jetzt schaue ich mir die Charge-Control von Arno an und ich bin gespannt, wie er das Thema jetzt im Detail programmiert hat. 
Also vielen Dank nochmal an alle.  Diese APP tut ja genau dass, was man ja eigentlich überall will.  Glätten des Sonnenenergieertrages vom Peak am Mittag auf den ganzen Tag.  
Herzliche Grüße 
Stefan

**Comment by git-kick** [comment]
.
