### ISSUE TITLE
Enhancement: enable writing into InfluxDB

### ISSUE THREAD

**Issue by github-ps1304** [git-kick/ioBroker.e3dc-rscp#163]
**Describe the bug**  
Enhancement: it would be great to write all values into a InfluxDB instance of iobroker. Otherwise you need to select each value.

**To Reproduce**  
a setting to pick an InfluxDB instance from iobroker would be great

**Expected behavior**  
write all or selected values into InfluxDB instance

**Comment by buanet** [comment]
Really? This is not how ioBroker works. Use Filters in Objects, then use the wrench button. You will be able to set influxdb settings for all object matching your filter!

For example: 
![image](https://github.com/git-kick/ioBroker.e3dc-rscp/assets/16137672/297371c7-6cb0-48ba-aa76-55d84a4f07cb)

![image](https://github.com/git-kick/ioBroker.e3dc-rscp/assets/16137672/b8b7edd8-f2da-48a3-8026-c9654c60c7b0)

Regards,
André

**Comment by github-ps1304** [comment]
I wasnt aware of that feature - cool; thanks for the headsup - will try it immediately. !!!
