### ISSUE TITLE
Keine werte von der Datenbank

### ISSUE THREAD

**Issue by SoerenR82** [git-kick/ioBroker.e3dc-rscp#164]
Hi, 

Ich würde gerne die daten aus der Datenbank von meinem S10 Pro Nutzen. Allerdings werden keine Werte angezeigt. 
js-controller 4.0.24
node.js: v18.16.0
Adapterverion 1.2.2 Ich hatte zuvfor die 1.1.0 Installiert. Dort hatte ich das selbe Problem. 

<img width="2333" alt="Bildschirmfoto 2023-05-18 um 14 04 41" src="https://github.com/git-kick/ioBroker.e3dc-rscp/assets/53448021/b6dbf82c-e57d-46e7-872e-7bd91fe1451c">

Ich nutze nur die Orginale APP von E3/DC vom auf das gerät zuzugreifen. Dort sind alle daten aus der Datenbank verfügbar. 
Sind im S10 Pro ggf. noch irgendwelche einstellungen zu machen um auf die History-Daten zugreifen zu können?

Gruße
Sören

**Comment by git-kick** [comment]
Hallo Sören,

du musst mind. einen der Werte TIME_START, TIME_SPAN, TIME_INTERVAL ändern. Kurz danach startet der Adapter die DB-Abfrage.

Das DB Thema ist noch "experimentell". Erste Erkenntnisse stehen im [ReadmeDev](https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/README-dev.md#db-namespace-semantics)

Grüße, Uli
