### ISSUE TITLE
Please consider fixing problems reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [git-kick/ioBroker.e3dc-rscp#166]
Please add missing languages. a simple ```npm run translate``` should do the joib if using the up-to-date release of dev-tools (https://github.com/ioBroker/adapter-dev)

Thanks for your support
McM1957

              ## Automated adapter checker

### [ioBroker.e3dc-rscp](https://github.com/git-kick/ioBroker.e3dc-rscp)
[![Downloads](https://img.shields.io/npm/dm/iobroker.e3dc-rscp.svg)](https://www.npmjs.com/package/iobroker.e3dc-rscp) ![Number of Installations (latest)](http://iobroker.live/badges/e3dc-rscp-installed.svg) ![Number of Installations (stable)](http://iobroker.live/badges/e3dc-rscp-stable.svg)
[![NPM](https://nodei.co/npm/iobroker.e3dc-rscp.png?downloads=true)](https://nodei.co/npm/iobroker.e3dc-rscp/)

:thumbsup: No errors found
- [x] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/io-package.json)
- [x] :eyes: [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [x] :eyes: [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

*Add comment "RE-CHECK!" to start check anew*

_Originally posted by @GermanBluefox in https://github.com/ioBroker/ioBroker.repositories/issues/2310#issuecomment-1563345786_

**Comment by git-kick** [comment]
I fixed the translation stuff and removed `gulpfile.js`

But after searching for an hour, I cannot figure out how to fix:

> [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI

@mcm1957, could you give me some starting point or template which I have to follow?

**Comment by ka-vaNu** [comment]
Perhaps you want to have a Look at my blebox-Adapter. I've implemented/configured a AdminUI5 https://github.com/ka-vaNu/ioBroker.blebox/blob/master/admin/jsonConfig.json

**Comment by git-kick** [comment]
Ok @mcm1957 , thanks for your quick check & response.
