### ISSUE TITLE
Warnings since update v1.2.1

### ISSUE THREAD

**Issue by Draygv2** [git-kick/ioBroker.e3dc-rscp#168]
**Describe the bug**  
i get this warnings:
<img width="719" alt="image" src="https://github.com/git-kick/ioBroker.e3dc-rscp/assets/62559741/bb91e175-4cda-48ed-8d16-22982d993019">

**Versions:**  
 - Adapter version: <1.2.1>
 - JS-Controller version: <18.15.0>
 - Node version: <9.6.5>
 - Operating system: <Ubuntu>

**Comment by git-kick** [comment]
This was reported with #159 
Solved in v1.2.2 (coming up).
Nevertheless, note that these warnings are a hint that traffic on your network may be somehow disturbed.
