### ISSUE TITLE
Abfrage Zählerstand

### ISSUE THREAD

**Issue by Berndhafen** [git-kick/ioBroker.e3dc-rscp#175]
Hallo,
ich benutze den Adapter um einige Parameter an KNX zu übergeben und dort auf der Visualisierung anzuzeigen.
Gibt es die Möglichkeit die Zähler für Produktion/Hausverbrauch/Netzbezug/Einspeisung auszulesen ? Evtl. für den aktuellen Tag, für den letzten Tag / Woche / Jahr ? einfache Anzeige in Wh oder kWh ? Im Prinzip die Werte die auch das E3DC Portal zur Verfügung stellt.
Vielen Dank.

**Comment by git-kick** [comment]
Hallo,
ja, die genannten Momentanwerte stehen alle im EMS Namespace. Kumulierte Werte kann man im DB Namespace abrufen. Das ist aber kaum dokumentiert, da muss man etwas mit den Werten spielen um zu verstehen, was die Anlage liefert.

**Comment by Berndhafen** [comment]
Danke für die schnelle Rückmeldung, die Momentanwerte habe ich, die frage ich auch ab, das klappt super. Aber im Ordner DB sind eben die History-Ordner und jeweils drei Zeit-Objekte aber keine Werte dazu.

**Comment by git-kick** [comment]
Du musst die Werte TIME_INTERVAL/_SPAN/_START setzen, das triggert die DB-Anfrage.

**Comment by Berndhafen** [comment]
Super, vielen Dank !!!
Genau das habe ich gesucht :-)

Danke & Grüße

**Comment by git-kick** [comment]
Da hilft nur Probieren.
Meine bescheidenen Erkenntnisse habe ich hier aufgeschrieben: https://github.com/git-kick/ioBroker.e3dc-rscp/blob/master/README-dev.md#db-namespace-semantics
