### ISSUE TITLE
Range Error in wallbox.js

### ISSUE THREAD

**Issue by git-kick** [git-kick/ioBroker.e3dc-rscp#190]
**Describe the bug**  
Sentry hat ca. 3500 Meldungen über einen Range Error in wallbox.js aufgefangen.
Offenbar wir der Int16 Wertebereich überschritten.

**To Reproduce**  
Fehler trat nicht bei mir auf, deshalb keine Prozedur zum reproduzieren.

**Expected behavior**  
Der Adapter sollte keine unbehandelten Exceptions werfen.

**Screenshots & Logfiles**  
[Sentry report](https://ulrich-kick.sentry.io/share/issue/81bdaf1430d944ac850a229a64860286/)
![grafik](https://github.com/git-kick/ioBroker.e3dc-rscp/assets/8932938/1685c334-c07d-478b-953c-7917909d34b3)

**Versions:**  
 - E3/DC model and battery type: unknown
 - Adapter version: 1.2.3
 - JS-Controller version: 5.0.13
 - Node version: 16.20.1
 - Operating system: linux

**Comment by git-kick** [comment]
@ka-vaNu, magst Du dir das mal ansehen?

**Comment by ka-vaNu** [comment]
Ja, mach ich gerne. Hab aber noch nicht mit sentry gearbeitet...

**Comment by git-kick** [comment]
Ich denke du musst nicht mit Sentry arbeiten.
Sentry meldet mittels "Abhörmodul" (das viele Adapter eingebaut haben) alle nicht gefangenen Exceptions aus allen Installationen des e3dc-rscp Adapters an sentry.io und dort werden sie gezählt und dargestellt, siehe Screenshot.

Wenn die Information nicht ausreicht, um das Problem einzugrenzen, dann schließen wir das Issue.
