### ISSUE TITLE
Polling Error im log

### ISSUE THREAD

**Issue by valbuz** [git-kick/ioBroker.e3dc-rscp#191]
**Describe the bug**  
Seit dem Update erhalte ich wieder Fehlermeldungen im Log.

**To Reproduce**  

Permanent vorhanden

**Screenshots & Logfiles**  
warn	TAG_INFO_REQ_GET_FS_USAGE has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_GET_FACILITY has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_GUI_TARGET has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_SW_RELEASE has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_TIME_ZONE has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_UTC_TIME has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_TIME has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_DHCP_STATUS has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_DNS has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_GATEWAY has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_MAC_ADDRESS has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_SUBNET_MASK has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_IP_ADDRESS has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_A35_SERIAL_NUMBER has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_MODULES_SW_VERSIONS has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_PRODUCTION_DATE has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_INFO_REQ_SERIAL_NUMBER has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_SYS_REQ_IS_SYSTEM_REBOOTING has no assigned polling interval - assuming 'M' - please check io-package.json
warn	TAG_EP_REQ_EP_RESERVE has no assigned polling interval - assuming 'M' - please check io-package.json

**Versions:**  
 - E3/DC S10E and battery ATL
 - Adapter version: 1.2.3
 - JS-Controller version: 18.17.1 
 - Node version: 18.17.1
 - Operating system: debian

Leider finde ich nicht die Möglichkeit das Polling dieser Werte zu deaktivieren in den Einstellungen.

Danke
Pat

**Comment by git-kick** [comment]
Bitte eine ganz neue Adapterkonfiguration anlegen.
siehe [README](https://github.com/git-kick/ioBroker.e3dc-rscp#reuse-of-adapter-configuration)
