### ISSUE TITLE
Mit Version 1.2.4 und eingeschalteter EMS oder EP schaltet sich der Solar Wechselrichter ab.

### ISSUE THREAD

**Issue by SurfGargano** [git-kick/ioBroker.e3dc-rscp#197]
**Describe the bug**  
Mit Version 1.2.4 und eingeschalteter EMS oder EP schaltet sich der Solar Wechselrichter ab.
V 1.2.3 funktioniert.

Die Debug Ausgabe gibt keinen Fehler aus.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

_In most cases, a debug-log of adapter startup (about 30 secs) will be helpful or neccessary._

**Versions:**  
 - E3/DC: \<model and battery type\>
 - Adapter version: \<adapter-version\>
 - JS-Controller version: \<js-controller-version\> _determine this with `iobroker -v` on the console_
 - Node version: \<node-version\> _determine this with `node -v` on the console_
 - Operating system: \<os-name and version\>

**Additional context**

**Comment by git-kick** [comment]
Danke für die Meldung, ich übernehme das in #196 in der Annahme, dass es das selbe Thema ist.
