### ISSUE TITLE
V1.2.4 initiates a reboot of the inverter any 5 minutes

### ISSUE THREAD

**Issue by gitty-jsu** [git-kick/ioBroker.e3dc-rscp#200]
After upgrading to V 1.2.4, my inverter began rebooting every 5 minutes.
The whole system was stable, only the inverter stopped, and startet producing again for another 5 minutes.
After changing the update intervall for "medium" from 5 minutes to 10 minutes, the reboots occured any 10 minutes.
I also had a ticket open et e3dc, but they said, its an external trigger on their logs.
After downgrading to 1.2.3 without changing the settings of the adapter, the inverter runs without any interruptions.
Does anybody else had this behaviour?
I´ll test again the next days and try to generate log outputs.
Best regards Jörg

**Comment by git-kick** [comment]
Duplicate. Please see #196
