### ISSUE TITLE
Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7

### ISSUE THREAD

**Issue by ESDN83** [git-kick/ioBroker.e3dc-rscp#212]
Since E3DC updated the Portal on 20th of Feb. I'm getting a warn in the logs at least every two minutes.

->>>    warn | Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7

debug log image attached below.

**Versions:**  
 - E3/DC:S S10 Pro
 - Adapter version: 1.2.5
 - JS-Controller version: 5.0.19
 - Node version:  v18.19.1
 - Operating system: Linux debian 6.1.0-18-amd64

![grafik](https://github.com/git-kick/ioBroker.e3dc-rscp/assets/92590362/7dca42fa-bc71-4990-bb21-c88360ce1f14)

**Comment by git-kick** [comment]
Please see #210 and #211

**Comment by git-kick** [comment]
see v1.2.6, currently in beta repo
