### ISSUE TITLE
Received data type ERROR

### ISSUE THREAD

**Issue by Gerhardptl** [git-kick/ioBroker.e3dc-rscp#218]
The following error is displayed in the iobroker logbook:

Received data type ERROR: RSCP_ERR_NOT_HANDLED (1) - tag TAG_WB_CONNECTED_DEVICES (0xe84101c)
Unknown tag: tagCode=0x100003e, len=4, typeCode=0x7

Whats the problem?
Can you help me?

**Comment by git-kick** [comment]
Please see #210 #211 #212.
Thx.

**Comment by git-kick** [comment]
see v1.2.6, currently in beta repo
