### ISSUE TITLE
PM Namespace is not shown in the instance

### ISSUE THREAD

**Issue by CRachfahl** [git-kick/ioBroker.e3dc-rscp#239]
First great adapter I love it.

My issue is that the PM namespace does not show up in the Apapter.

I have an S20 X Pro 

Thanks in advance

Carsten

![Screenshot 2024-10-07 193115](https://github.com/user-attachments/assets/22860cc1-cd8a-4a68-99c1-90f6de1934e4)

**Comment by git-kick** [comment]
Hallo Carsten,

- welche Version des e3dc-rscp-Adapters hat du installiert?
- ist "PM" in deiner Instanz-Konfiguration ausgewählt?
![grafik](https://github.com/user-attachments/assets/5ad16fbf-eaa5-45b2-bf7c-f3929ad144f2)

**Comment by CRachfahl** [comment]
Hi Uli,

habe eben gesehen das du in dem neuen Adapter die PM drin hast. Ich habe noch 1.2.6 installiert allerdings bietet er mir das Update nicht an.

Und danke für die herforagende Arbeit!!!

Carsten

________________________________

**Comment by git-kick** [comment]
Die v1.3.1 war bis heute noch im beta-Status, jetzt sollte sie aber auch im stable-Repo erscheinen.
