### ISSUE TITLE
Device Discovery

### ISSUE THREAD

**Issue by git-kick** [git-kick/ioBroker.e3dc-rscp#67]
Add a discovery interface for E3/DC devices, supposedly using uPnP.

> You do not "need to" have a discovery ... If your dapter integrates devices that can be discovered then it would be great to add to discovery adapter.
> 
> So IF it is possible then you need to do a PR for https://github.com/ioBroker/ioBroker.discovery/tree/master/lib/adapters and addyour file there to detect a device.
> In fact discovery will scan all IPs in the network but can also do mdns or udp

Source: https://github.com/ioBroker/ioBroker.repositories/pull/1589

**Comment by git-kick** [comment]
e3dc-rscp discovery is up and running.
But the discovery `e3dc-rscp.js` file is large because it duplicates all the polling interval defaults.
Requested advice by @apollon77

**Comment by Apollon77** [comment]
Do you have a code link?

**Comment by git-kick** [comment]
Yes: https://github.com/git-kick/ioBroker.discovery/blob/master/lib/adapters/e3dc-rscp.js

**Comment by git-kick** [comment]
[PR#213](https://github.com/ioBroker/ioBroker.discovery/pull/213) is waiting for approval

**Comment by git-kick** [comment]
[PR#213](https://github.com/ioBroker/ioBroker.discovery/pull/213) is merged into master, but `discovery@2.7.5` still does not find E3/DC.
Wait for `discovery>2.7.5`

**Comment by Apollon77** [comment]
No, wait for 2.8.0 please ...see Discovery changelog https://github.com/ioBroker/ioBroker.discovery#280-2022-02-20

**Comment by git-kick** [comment]
Tested o.k. with `discovery@3.0.2`
