### ISSUE TITLE
Werte State "e3dc-rscp.0.WB.WB_0.PM_ACTIVE_PHASES" decodieren.

### ISSUE THREAD

**Issue by ArnoD15** [git-kick/ioBroker.e3dc-rscp#76]
Hallo Uli,

kannst du Bitte den State "e3dc-rscp.0.WB.WB_0.PM_ACTIVE_PHASES" gleich decodieren wie "e3dc-rscp.0.EMS.BALANCED_PHASES"

"states": {
      "0": "PHASE_000",
      "1": "PHASE_001",
      "2": "PHASE_010",
      "3": "PHASE_011",
      "4": "PHASE_100",
      "5": "PHASE_101",
      "6": "PHASE_110",
      "7": "PHASE_111"
    },

**Comment by git-kick** [comment]
Klar, wird gemacht. Danke, Arno!

**Comment by git-kick** [comment]
Kommt mit v1.0.2
Bitte testen (ich kann es ja mangels WB nicht).

**Comment by ArnoD15** [comment]
Sorry, habe vergessen, dir hier zu antworten.
Ist enthalten und funktioniert, Issue kann somit geschlossen werden.
Danke
