### ISSUE TITLE
Dear git-kick

### ISSUE THREAD

**Issue by Hanspi59** [git-kick/ioBroker.e3dc-rscp#91]
First I thank you for this great project! It works great.
Is it eventually possible to integrate the kwh calculation? 
If I use the E3DC Android App I can see the data in kwh. It would be very helpful ;-)
Many thanks for your help
cheers
HP

**Comment by git-kick** [comment]
@Hanspi59 , thank you for using the adapter and for your suggestion.

Nevertheless, I tend to not implement it:
1. The adapter "standard mode" is to present values as delivered from the interface. Calculations are only done in exceptional cases, where specific knowledge is involved (example is DB.HISTORY_DATA). The adapter is not intended to serve as a comfortable user interface.
2. The change would possibly break existing JS scripts using the values - ther are >180 installations out there already.

I hope for your understanding.
