### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by bushmills1608** [git-kick/ioBroker.e3dc-rscp#93]
The Connection is not stable.
![grafik](https://user-images.githubusercontent.com/82402958/159050965-43489367-8324-43d4-903d-20c746cf963f.png)
V1.02

**Comment by git-kick** [comment]
Looks like a site-specific issue.
If you think it is worth, then please find steps to reproduce the problem and fill the bug report form, including a complete description of your installation.

**Comment by bushmills1608** [comment]
Sehr gerne, 
leider weiß ich nicht wo ich den bug report form ausfüllen kann.

**Comment by git-kick** [comment]
Wenn man den Button "New Issue" wählt, gibt es bei "Bug Report" einen Button "Get Started". Damit öffnet sich ein neuer Issue mit den entsprechenden Abschnitten.

**Comment by bushmills1608** [comment]
ich finde dummerweise keinen Button "New Issue"

**Comment by git-kick** [comment]
Hmm, hab ichs nicht richtig beschrieben? Also bitte erstmal hierher:
https://github.com/git-kick/ioBroker.e3dc-rscp/issues
Das sollte dan oben so aussehen:
![grafik](https://user-images.githubusercontent.com/8932938/159172401-bf014bc4-7e9c-4dc6-88c4-42c077684f0d.png)
Da ist rechts in grün "New Issue", wenn du den drückst kommt:
![grafik](https://user-images.githubusercontent.com/8932938/159172435-28fdbb12-5ea2-487b-94cc-0dc66658e929.png)
... und mit "Get started" gehts los.

**Comment by git-kick** [comment]
Ersetzt durch [Issue#97](https://github.com/git-kick/ioBroker.e3dc-rscp/issues/97)
